### ISSUE TITLE
Potentially Redundant Variable

### ISSUE THREAD

**Issue by Valkryst** [AndyBobBean/PathFinding#1]
I believe the `_destinationFound` variable, used in *BreadthFirst.cs* can be removed without affecting the algorithm. Although I could be wrong.

**Comment by AndyBobBean** [comment]
Hi Valkryst, thanks for looking, but _destinationFound is used on line 23 and 47 of that file to make sure the algorithm doesn't keep running after it's found the destination node.

**Comment by Valkryst** [comment]
Ah, yeah. I just noticed the `&&` isn't an `||` in the while loop.
