### ISSUE TITLE
Not supported in lower version Visual Studio

### ISSUE THREAD

**Issue by goldsail** [AndyBobBean/PathFinding#3]
It seems this project is supported by Visual Studio 2017 only, as it uses .NET Core XML files that Visual Studio 2015 does not support.

**Comment by AndyBobBean** [comment]
I will re-code the Grid and Algorithms projects so that they work in Visual Studio 2015 and upload the changes later today.

**Comment by AndyBobBean** [comment]
I've pushed the updates, the code now works with Visual Studio 2015 at least. I have not tried 2013 or lower, but I think it would probably be fine.
